import avatar from "./assets/images/avatar.jpg";

const blogData = [
  {
    id: 1,
    image: `https://unsplash.com/photos/depth-of-field-photography-of-man-playing-chess-fzOITuS1DIQ`,
    category: "Technology",
    title: "The Future of AI: Trends to Watch in 2024",
    authorImage: avatar,
    authorName: "John Doe",
    date: "February 5, 2024",
  },
  {
    id: 2,
    image: `https://unsplash.com/photos/depth-of-field-photography-of-man-playing-chess-fzOITuS1DIQ`,
    category: "Travel",
    title: "Exploring Hidden Gems: Off the Beaten Path Destinations",
    authorImage: avatar,
    authorName: "Jane Smith",
    date: "February 3, 2024",
  },
  {
    id: 3,
    image: `https://unsplash.com/photos/depth-of-field-photography-of-man-playing-chess-fzOITuS1DIQ`,
    category: "Food",
    title: "10 Mouthwatering Recipes to Impress Your Guests",
    authorImage: avatar,
    authorName: "Michael Johnson",
    date: "February 1, 2024",
  },
  {
    id: 4,
    image: `https://unsplash.com/photos/depth-of-field-photography-of-man-playing-chess-fzOITuS1DIQ`,
    category: "Fitness",
    title: "5 Essential Exercises for Building Muscle Mass",
    authorImage: avatar,
    authorName: "Emily Brown",
    date: "January 28, 2024",
  },
  {
    id: 5,
    image: `https://unsplash.com/photos/depth-of-field-photography-of-man-playing-chess-fzOITuS1DIQ`,
    category: "Fashion",
    title: "Trend Alert: Sustainable Fashion for a Greener Planet",
    authorImage: avatar,
    authorName: "David Wilson",
    date: "January 25, 2024",
  },
  {
    id: 6,
    image: `https://unsplash.com/photos/depth-of-field-photography-of-man-playing-chess-fzOITuS1DIQ`,
    category: "Health",
    title: "The Importance of Mental Health: Tips for Self-Care",
    authorImage: avatar,
    authorName: "Sarah Thompson",
    date: "January 20, 2024",
  },
  {
    id: 7,
    image: `https://unsplash.com/photos/depth-of-field-photography-of-man-playing-chess-fzOITuS1DIQ`,
    category: "Finance",
    title: "Investing 101: A Beginner's Guide to Financial Freedom",
    authorImage: avatar,
    authorName: "Alex Johnson",
    date: "January 15, 2024",
  },
  {
    id: 8,
    image: `https://unsplash.com/photos/depth-of-field-photography-of-man-playing-chess-fzOITuS1DIQ`,
    category: "DIY",
    title: "Creative Home Decor Ideas to Transform Your Space",
    authorImage: avatar,
    authorName: "Sophia Garcia",
    date: "January 10, 2024",
  },
  {
    id: 9,
    image: `https://unsplash.com/photos/depth-of-field-photography-of-man-playing-chess-fzOITuS1DIQ`,
    category: "Education",
    title: "Effective Study Techniques for Academic Success",
    authorImage: avatar,
    authorName: "Daniel Miller",
    date: "January 5, 2024",
  },
  {
    id: 10,
    image: `https://unsplash.com/photos/depth-of-field-photography-of-man-playing-chess-fzOITuS1DIQ`,
    category: "Lifestyle",
    title: "Finding Balance: Tips for Juggling Work and Personal Life",
    authorImage: avatar,
    authorName: "Olivia Wilson",
    date: "January 1, 2024",
  },
];

export default blogData;
